In [52]:
import pandas as pd

In [54]:
df = pd.read_excel('data2.xlsx')
df

,Actor Name,Genre,Film,Year,Box Office (Cr),IMDb Rating
0,Salman Khan,Action,Sultan,2016.0,623.0,7.0
1,Aamir Khan,Drama,Dangal,2016.0,2024.0,8.4
2,Ranbir Kapoor,Romance,Yeh Jawaani Hai Deewani,2013.0,319.0,7.2
3,Ranveer Singh,Historical,Padmaavat,2018.0,585.0,7.0
4,Amitabh Bachchan,Thriller,Pink,2016.0,77.0,8.1
5,Vicky Kaushal,War,Uri,2019.0,342.0,8.4
6,Rajkummar Rao,Crime,Shahid,2013.0,4.0,8.2
7,etc...,NaN,NaN,NaN,NaN,NaN

In [ ]:
df['Actor Name']

0           Shah Rukh Khan
1              Salman Khan
2               Aamir Khan
3           Hrithik Roshan
4            Ranbir Kapoor
5             Akshay Kumar
6            Ranveer Singh
7         Amitabh Bachchan
8       Ayushmann Khurrana
9            Rajkummar Rao
10           Vicky Kaushal
11     Nawazuddin Siddiqui
12    Sushant Singh Rajput
13              Ajay Devgn
14            Varun Dhawan
15            Tiger Shroff
16            John Abraham
Name: Actor Name, dtype: object

In [ ]:
df['Actor Name'][3]

'Hrithik Roshan'

In [ ]:
df[['Actor Name','Year']]

              Actor Name  Year
0         Shah Rukh Khan  1995
1            Salman Khan  2016
2             Aamir Khan  2016
3         Hrithik Roshan  2019
4          Ranbir Kapoor  2013
5           Akshay Kumar  2000
6          Ranveer Singh  2018
7       Amitabh Bachchan  2016
8     Ayushmann Khurrana  2019
9          Rajkummar Rao  2013
10         Vicky Kaushal  2019
11   Nawazuddin Siddiqui  2012
12  Sushant Singh Rajput  2018
13            Ajay Devgn  2011
14          Varun Dhawan  2017
15          Tiger Shroff  2016
16          John Abraham  2019

In [ ]:
# this only returns a copy

In [ ]:
df.loc[1]

Actor Name         Salman Khan
Genre                   Action
Film                    Sultan
Year                      2016
Box Office (Cr)            623
IMDb Rating                7.0
Name: 1, dtype: object

In [ ]:
df.iloc[1]

Actor Name         Salman Khan
Genre                   Action
Film                    Sultan
Year                      2016
Box Office (Cr)            623
IMDb Rating                7.0
Name: 1, dtype: object

In [ ]:
df.loc[8,'Actor Name']  # Accessing a specific cell using label-based indexing

'Ayushmann Khurrana'

In [ ]:
df.iloc[8,5]

7.0

In [ ]:
df.loc[0:2, ["Actor Name", "Year","Film"]]

       Actor Name  Year                         Film
0  Shah Rukh Khan  1995  Dilwale Dulhania Le Jayenge
1     Salman Khan  2016                       Sultan
2      Aamir Khan  2016                       Dangal

In [ ]:
df.iloc[0:2, 0:2]

       Actor Name    Genre
0  Shah Rukh Khan  Romance
1     Salman Khan   Action

In [ ]:
df.at[0,"Actor Name"]  # Accessing a specific cell using label-based indexing

'Shah Rukh Khan'

In [ ]:
df[df['IMDb Rating'] > 6]['Actor Name']

0           Shah Rukh Khan
1              Salman Khan
2               Aamir Khan
3           Hrithik Roshan
4            Ranbir Kapoor
5             Akshay Kumar
6            Ranveer Singh
7         Amitabh Bachchan
8       Ayushmann Khurrana
9            Rajkummar Rao
10           Vicky Kaushal
11     Nawazuddin Siddiqui
12    Sushant Singh Rajput
13              Ajay Devgn
16            John Abraham
Name: Actor Name, dtype: object

In [ ]:
df[(df['IMDb Rating'] > 6) & (df['Year'] > 2000)]

,Actor Name,Genre,Film,Year,Box Office (Cr),IMDb Rating
1,Salman Khan,Action,Sultan,2016,623,7.0
2,Aamir Khan,Drama,Dangal,2016,2024,8.4
3,Hrithik Roshan,Action,War,2019,475,6.5
4,Ranbir Kapoor,Romance,Yeh Jawaani Hai Deewani,2013,319,7.2
6,Ranveer Singh,Historical,Padmaavat,2018,585,7.0
7,Amitabh Bachchan,Thriller,Pink,2016,77,8.1
8,Ayushmann Khurrana,Comedy,Dream Girl,2019,200,7.0
9,Rajkummar Rao,Crime,Shahid,2013,4,8.2
10,Vicky Kaushal,War,Uri: The Surgical Strike,2019,342,8.4
11,Nawazuddin Siddiqui,Crime,Gangs of Wasseypur,2012,28,8.2
12,Sushant Singh Rajput,Romance,Kedarnath,2018,96,6.8
13,Ajay Devgn,Action,Singham,2011,140,6.8
16,John Abraham,Action,Batla House,2019,111,7.2

In [ ]:
df[(df['IMDb Rating'] > 6) | (df['Year'] > 2000)]

,Actor Name,Genre,Film,Year,Box Office (Cr),IMDb Rating
0,Shah Rukh Khan,Romance,Dilwale Dulhania Le Jayenge,1995,102,8.0
1,Salman Khan,Action,Sultan,2016,623,7.0
2,Aamir Khan,Drama,Dangal,2016,2024,8.4
3,Hrithik Roshan,Action,War,2019,475,6.5
4,Ranbir Kapoor,Romance,Yeh Jawaani Hai Deewani,2013,319,7.2
5,Akshay Kumar,Comedy,Hera Pheri,2000,25,8.1
6,Ranveer Singh,Historical,Padmaavat,2018,585,7.0
7,Amitabh Bachchan,Thriller,Pink,2016,77,8.1
8,Ayushmann Khurrana,Comedy,Dream Girl,2019,200,7.0
9,Rajkummar Rao,Crime,Shahid,2013,4,8.2
10,Vicky Kaushal,War,Uri: The Surgical Strike,2019,342,8.4
11,Nawazuddin Siddiqui,Crime,Gangs of Wasseypur,2012,28,8.2
12,Sushant Singh Rajput,Romance,Kedarnath,2018,96,6.8
13,Ajay Devgn,Action,Singham,2011,140,6.8
14,Varun Dhawan,Comedy,Judwaa 2,2017,227,4.7
15,Tiger Shroff,Action,Baaghi,2016,127,5.2
16,John Abraham,Action,Batla House,2019,111,7.2

In [ ]:
df.query('`IMDb Rating` > 6 and Year > 2000')

,Actor Name,Genre,Film,Year,Box Office (Cr),IMDb Rating
1,Salman Khan,Action,Sultan,2016,623,7.0
2,Aamir Khan,Drama,Dangal,2016,2024,8.4
3,Hrithik Roshan,Action,War,2019,475,6.5
4,Ranbir Kapoor,Romance,Yeh Jawaani Hai Deewani,2013,319,7.2
6,Ranveer Singh,Historical,Padmaavat,2018,585,7.0
7,Amitabh Bachchan,Thriller,Pink,2016,77,8.1
8,Ayushmann Khurrana,Comedy,Dream Girl,2019,200,7.0
9,Rajkummar Rao,Crime,Shahid,2013,4,8.2
10,Vicky Kaushal,War,Uri: The Surgical Strike,2019,342,8.4
11,Nawazuddin Siddiqui,Crime,Gangs of Wasseypur,2012,28,8.2
12,Sushant Singh Rajput,Romance,Kedarnath,2018,96,6.8
13,Ajay Devgn,Action,Singham,2011,140,6.8
16,John Abraham,Action,Batla House,2019,111,7.2

In [ ]:
df.query("`Actor Name` == 'Ajay Devgn'")

    Actor Name   Genre     Film  Year  Box Office (Cr)  IMDb Rating
13  Ajay Devgn  Action  Singham  2011              140          6.8

In [ ]:
df.query("2000 < Year < 2020 ")

,Actor Name,Genre,Film,Year,Box Office (Cr),IMDb Rating
1,Salman Khan,Action,Sultan,2016,623,7.0
2,Aamir Khan,Drama,Dangal,2016,2024,8.4
3,Hrithik Roshan,Action,War,2019,475,6.5
4,Ranbir Kapoor,Romance,Yeh Jawaani Hai Deewani,2013,319,7.2
6,Ranveer Singh,Historical,Padmaavat,2018,585,7.0
7,Amitabh Bachchan,Thriller,Pink,2016,77,8.1
8,Ayushmann Khurrana,Comedy,Dream Girl,2019,200,7.0
9,Rajkummar Rao,Crime,Shahid,2013,4,8.2
10,Vicky Kaushal,War,Uri: The Surgical Strike,2019,342,8.4
11,Nawazuddin Siddiqui,Crime,Gangs of Wasseypur,2012,28,8.2
12,Sushant Singh Rajput,Romance,Kedarnath,2018,96,6.8
13,Ajay Devgn,Action,Singham,2011,140,6.8
14,Varun Dhawan,Comedy,Judwaa 2,2017,227,4.7
15,Tiger Shroff,Action,Baaghi,2016,127,5.2
16,John Abraham,Action,Batla House,2019,111,7.2

In [ ]:
#  always use case sensitivity in query
df.query("`Actor Name` == 'Ajay Devgn' and `IMDb Rating` > 6")

    Actor Name   Genre     Film  Year  Box Office (Cr)  IMDb Rating
13  Ajay Devgn  Action  Singham  2011              140          6.8